Add Ostrava Pyladies autumn 2022 course
messa/pyladies-courseware pull request #409
Opened 2022-10-05 13:48 UTC by petracihalova

2022-10-05 13:48 UTC, petracihalova commented
sorry wrong branch

2022-10-05 13:51 UTC, petracihalova commented
didn't know that it is possible to change the base branch 😁😁😁 so now is ready for review

2022-10-05 20:37 UTC, frenzymadness requested changes
Po pár drobných opravách se mi to rozjelo. Nekontroloval jsem obsah, ale jen funkčnost.

2022-10-05 20:37 UTC, frenzymadness commented on data/2022_pyladies_ostrava_autumn/course.yaml
> +  - file: tasks/loops.yaml
```suggestion
  - file: tasks/03_loops.yaml
```

2022-10-05 20:37 UTC, frenzymadness commented on data/2022_pyladies_ostrava_autumn/tasks/01_variables.yaml
> +- id handout1_16
```suggestion
- id: handout1_16
```

2022-10-05 20:37 UTC, frenzymadness commented on data/2022_pyladies_ostrava_autumn/tasks/06_exceptions.yaml
> +section:
```suggestion
- section:
```

2022-10-07 11:43 UTC, petracihalova commented
@frenzymadness připraveno na review, snad už žádné změny nebudeme potřebovat

2022-10-07 12:44 UTC, frenzymadness commented
Stačí funkční review nebo mám koukat i na obsah jednotlivých úloh a jejich propojení s obsahem kurzu?

2022-10-07 13:05 UTC, petracihalova commented
jak chceš 😁 ale kontrolovala jsem to a mělo by to být všechno ok

2022-10-09 12:36 UTC, frenzymadness approved these changes
Udělal jsem zevrubnou kontrolu a vše je v pohodě. Mám udělat squash a merge nebo to chceš dělat ručně?

2022-10-09 13:29 UTC, petracihalova commented
ručně ... je to hotovo

2022-10-10 08:53 UTC, merged